src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

src/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

src/cart/models.py
from django.db import models

# Create your models here.

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity =  forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        widget=forms.Select(attrs={
            'class': 'border-info'
        }))
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput)

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CartAddProductForm
from .cart import Cart
from shop.models import Product
from django.views.decorators.http import require_POST


@require_POST
def cart_add(request, product_id):
    # call __init__ of Cart class
    # to get the session cart or create one
    cart = Cart(request)
    # get the product from the database
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)    
    
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )
    return render(request, 'cart/detail.html', {'cart': cart})

src/cart/templates/cart/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load shop_tags %}

{% block title %}Your shopping cart{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card border-light">
                    <div class="card-body">
                        <h4 class="card-title">Your cart</h4>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Remove</th>
                                    <th>Unit Price</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr>
                                            <td>
                                                <a href="{{ product.get_absolute_url }}">
                                                    <img class="product-cart-img" src="{{ product.image.url }}" alt="">
                                                </a>
                                            </td>
                                            <td>{{ product.name }}</td>
                                            <td>
                                                <form method="POST" action="{% url 'cart:cart_add' product.id %}" class="form-group">
                                                    <div class="d-flex">
                                                        {{ item.update_quantity_form.quantity }}
                                                        {{ item.update_quantity_form.override }}
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-info btn-sm"><i class="fas fa-redo"></i> Update</button>
                                                    </div>
                                                </form>
                                            </td>
                                            <td>
                                                <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                                                    <button type="submit" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i> Remove</button>
                                                    {% csrf_token %}
                                                </form>
                                            </td>
                                            <td class="">${{ item.price|apply_thousand_seperator }}</td>
                                            <td class="">${{ item.total_price|apply_thousand_seperator }}</td>
                                        </tr>
                                    {% endwith %}
                                {% empty %}
                                <tr>
                                    <td colspan="6">
                                        <p class="card-text">No item in your cart</p>
                                    </td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td>Subtotal</td>
                                    <td colspan="4"></td>
                                    <td><strong>${{ cart.get_total_price|apply_thousand_seperator }}</strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <hr>
                        <p class="text-right mb-5">
                            <a class="btn btn-outline-info" href="{% url 'shop:product_list' %}">Continue shopping</a>
                            <a class="btn btn-primary" href="{% url 'orders:order_create' %}">Checkout</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}